import type { CSSProperties } from "react";

export const scheduleClubEventsStyles = {
    actionsTop: {
        display: "grid",
        gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
        gap: "8px",
    },
    primaryActionButton: {
        minHeight: "40px",
        padding: "0 12px",
        borderRadius: "12px",
        border: "1px solid rgba(106,179,243,0.24)",
        background: "linear-gradient(180deg, rgba(42,129,186,0.98) 0%, rgba(28,112,168,0.98) 100%)",
        color: "#ffffff",
        fontSize: "12px",
        fontWeight: 700,
        letterSpacing: "0.02em",
        cursor: "pointer",
        boxShadow: "0 10px 20px rgba(0,0,0,0.16)",
    },
    text: {
        margin: 0,
        fontSize: "13px",
        lineHeight: 1.5,
        color: "var(--tg-theme-hint-color, rgba(255,255,255,0.7))",
    },
    list: {
        display: "grid",
        gap: "8px",
    },
    topRow: {
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: "10px",
    },
    eventRow: {
        display: "grid",
        gridTemplateColumns: "minmax(0, 1fr) auto",
        alignItems: "center",
        gap: "8px",
        padding: "10px 12px",
        borderRadius: "12px",
        border: "1px solid rgba(255,255,255,0.08)",
        background: "rgba(255,255,255,0.03)",
    },
    eventRowButton: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        minWidth: 0,
        padding: 0,
        border: 0,
        background: "transparent",
        color: "inherit",
        cursor: "pointer",
        textAlign: "left",
    },
    rowActions: {
        display: "flex",
        alignItems: "center",
        gap: "6px",
    },
    eventDate: {
        margin: 0,
        fontSize: "12px",
        fontWeight: 700,
        letterSpacing: "0.04em",
        textTransform: "uppercase",
        color: "var(--tg-theme-button-color, #6ab3f3)",
        paddingTop: "6px",
    },
    eventHeader: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "20px",
        padding: 0,
        color: "#9ed0ff",
        fontSize: "12px",
        fontWeight: 700,
        letterSpacing: "0.04em",
        textTransform: "uppercase",
    },
    trainingHeader: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "20px",
        padding: 0,
        color: "#ff8f8f",
        fontSize: "12px",
        fontWeight: 700,
        letterSpacing: "0.04em",
        textTransform: "uppercase",
    },
    eventRowTitle: {
        minWidth: 0,
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
        fontSize: "14px",
        fontWeight: 700,
        color: "var(--tg-theme-text-color, #ffffff)",
    },
    eventRowMeta: {
        flexShrink: 0,
        fontSize: "12px",
        color: "var(--tg-theme-hint-color, rgba(255,255,255,0.66))",
        whiteSpace: "nowrap",
    },
    eventTitle: {
        margin: 0,
        fontSize: "14px",
        fontWeight: 700,
        color: "var(--tg-theme-text-color, #ffffff)",
    },
    eventMeta: {
        margin: 0,
        fontSize: "12px",
        lineHeight: 1.45,
        color: "var(--tg-theme-hint-color, rgba(255,255,255,0.72))",
    },
    actionsRow: {
        display: "flex",
        flexWrap: "wrap",
        gap: "8px",
        marginTop: "4px",
    },
    joinButton: {
        justifySelf: "start",
        minHeight: "34px",
        padding: "0 12px",
        borderRadius: "10px",
        border: "1px solid rgba(106,179,243,0.35)",
        background: "linear-gradient(180deg, rgba(50,73,100,0.98) 0%, rgba(38,55,75,0.98) 100%)",
        color: "#9ed0ff",
        fontSize: "11px",
        fontWeight: 700,
        cursor: "pointer",
    },
    cancelButton: {
        justifySelf: "start",
        minHeight: "34px",
        padding: "0 12px",
        borderRadius: "10px",
        border: "1px solid rgba(255,255,255,0.18)",
        background: "linear-gradient(180deg, rgba(40,52,67,0.96) 0%, rgba(31,42,56,0.96) 100%)",
        color: "#ffffff",
        fontSize: "11px",
        fontWeight: 700,
        cursor: "pointer",
    },
    editButton: {
        minHeight: "34px",
        padding: "0 12px",
        borderRadius: "10px",
        border: "1px solid rgba(255,255,255,0.18)",
        background: "linear-gradient(180deg, rgba(40,52,67,0.96) 0%, rgba(31,42,56,0.96) 100%)",
        color: "#ffffff",
        fontSize: "11px",
        fontWeight: 700,
        cursor: "pointer",
    },
    deleteButton: {
        minHeight: "34px",
        padding: "0 12px",
        borderRadius: "10px",
        border: "1px solid rgba(255,138,160,0.35)",
        background: "linear-gradient(180deg, rgba(80,44,54,0.92) 0%, rgba(64,37,45,0.92) 100%)",
        color: "#ff9fb1",
        fontSize: "11px",
        fontWeight: 700,
        cursor: "pointer",
    },
    joinButtonCompact: {
        minHeight: "28px",
        padding: "0 10px",
        borderRadius: "9px",
        border: "1px solid rgba(106,179,243,0.35)",
        background: "linear-gradient(180deg, rgba(50,73,100,0.98) 0%, rgba(38,55,75,0.98) 100%)",
        color: "#9ed0ff",
        fontSize: "11px",
        fontWeight: 700,
        cursor: "pointer",
    },
    cancelButtonCompact: {
        minHeight: "28px",
        padding: "0 10px",
        borderRadius: "9px",
        border: "1px solid rgba(255,255,255,0.18)",
        background: "linear-gradient(180deg, rgba(40,52,67,0.96) 0%, rgba(31,42,56,0.96) 100%)",
        color: "#ffffff",
        fontSize: "11px",
        fontWeight: 700,
        cursor: "pointer",
    },
    editButtonCompact: {
        minHeight: "28px",
        padding: "0 10px",
        borderRadius: "9px",
        border: "1px solid rgba(255,255,255,0.18)",
        background: "linear-gradient(180deg, rgba(40,52,67,0.96) 0%, rgba(31,42,56,0.96) 100%)",
        color: "#ffffff",
        fontSize: "11px",
        fontWeight: 700,
        cursor: "pointer",
    },
    detailsOverlay: {
        position: "fixed",
        inset: 0,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "rgba(0,0,0,0.56)",
        zIndex: 1000,
        padding: "16px",
    },
    detailsModal: {
        position: "relative",
        width: "100%",
        maxWidth: "460px",
        display: "grid",
        gap: "10px",
        padding: "16px",
        borderRadius: "16px",
        background: "#17212b",
        border: "1px solid rgba(255,255,255,0.08)",
    },
    detailsClose: {
        position: "absolute",
        top: "10px",
        right: "10px",
        width: "30px",
        height: "30px",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        borderRadius: "999px",
        border: "1px solid rgba(255,255,255,0.12)",
        background: "rgba(255,255,255,0.04)",
        color: "#ffffff",
        fontSize: "18px",
        cursor: "pointer",
    },
    detailsType: {
        fontSize: "12px",
        fontWeight: 700,
        letterSpacing: "0.06em",
        textTransform: "uppercase",
        color: "#9ed0ff",
    },
    detailsTitle: {
        margin: 0,
        fontSize: "22px",
        lineHeight: 1.2,
        color: "#ffffff",
    },
    detailsMetaList: {
        display: "grid",
        gap: "8px",
    },
    detailsMetaRow: {
        margin: 0,
        fontSize: "14px",
        lineHeight: 1.5,
        color: "rgba(255,255,255,0.78)",
        whiteSpace: "pre-line",
    },
    detailsActions: {
        display: "flex",
        flexWrap: "wrap",
        gap: "8px",
        marginTop: "6px",
    },
} satisfies Record<string, CSSProperties>;
