import type { CSSProperties } from "react";

export const scheduleClubEventsStyles = {
    text: {
        margin: 0,
        fontSize: "14px",
        lineHeight: 1.5,
        color: "var(--tg-theme-hint-color, rgba(255,255,255,0.7))",
    },
    list: {
        display: "grid",
        gap: "10px",
    },
    topRow: {
        display: "flex",
        alignItems: "flex-start",
        justifyContent: "space-between",
        gap: "10px",
    },
    eventItem: {
        display: "grid",
        gap: "6px",
        padding: "14px 16px",
        borderRadius: "14px",
        border: "1px solid rgba(255,255,255,0.08)",
        background: "rgba(255,255,255,0.03)",
    },
    eventDate: {
        margin: 0,
        fontSize: "12px",
        fontWeight: 700,
        letterSpacing: "0.04em",
        textTransform: "uppercase",
        color: "var(--tg-theme-button-color, #6ab3f3)",
        paddingTop: "6px",
    },
    eventHeader: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "20px",
        padding: 0,
        color: "#9ed0ff",
        fontSize: "12px",
        fontWeight: 700,
        letterSpacing: "0.04em",
        textTransform: "uppercase",
    },
    trainingHeader: {
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "20px",
        padding: 0,
        color: "#ff8f8f",
        fontSize: "12px",
        fontWeight: 700,
        letterSpacing: "0.04em",
        textTransform: "uppercase",
    },
    eventTitle: {
        margin: 0,
        fontSize: "16px",
        fontWeight: 700,
        color: "var(--tg-theme-text-color, #ffffff)",
    },
    eventMeta: {
        margin: 0,
        fontSize: "13px",
        lineHeight: 1.45,
        color: "var(--tg-theme-hint-color, rgba(255,255,255,0.72))",
    },
    actionsRow: {
        display: "flex",
        flexWrap: "wrap",
        gap: "8px",
        marginTop: "4px",
    },
    joinButton: {
        justifySelf: "start",
        minHeight: "34px",
        padding: "0 12px",
        borderRadius: "10px",
        border: "1px solid rgba(106,179,243,0.35)",
        background: "rgba(106,179,243,0.10)",
        color: "#9ed0ff",
        fontSize: "12px",
        fontWeight: 700,
        cursor: "pointer",
    },
    cancelButton: {
        justifySelf: "start",
        minHeight: "34px",
        padding: "0 12px",
        borderRadius: "10px",
        border: "1px solid rgba(255,255,255,0.18)",
        background: "rgba(255,255,255,0.05)",
        color: "#ffffff",
        fontSize: "12px",
        fontWeight: 700,
        cursor: "pointer",
    },
    editButton: {
        minHeight: "34px",
        padding: "0 12px",
        borderRadius: "10px",
        border: "1px solid rgba(255,255,255,0.18)",
        background: "rgba(255,255,255,0.05)",
        color: "#ffffff",
        fontSize: "12px",
        fontWeight: 700,
        cursor: "pointer",
    },
    deleteButton: {
        minHeight: "34px",
        padding: "0 12px",
        borderRadius: "10px",
        border: "1px solid rgba(255,138,160,0.35)",
        background: "rgba(255,138,160,0.10)",
        color: "#ff9fb1",
        fontSize: "12px",
        fontWeight: 700,
        cursor: "pointer",
    },
} satisfies Record<string, CSSProperties>;
