// frontend/src/pages/shop/styles/shopShowcase.styles.ts
export const shopShowcaseStyles = {
    showcaseLayout: {
        display: "grid",
        gridTemplateColumns: "minmax(160px, 42%) 1fr",
        gap: 14,
        alignItems: "start" as const,
    },
    showcaseMenu: {
        display: "flex",
        flexDirection: "column" as const,
        gap: 12,
    },
    menuItem: {
        display: "flex",
        alignItems: "center" as const,
        gap: 10,
        padding: "12px 14px",
        borderRadius: 2,
        border: "1px solid rgba(201, 162, 74, 0.55)",
        background: "rgba(0, 0, 0, 0.35)",
        cursor: "pointer",
        color: "#c9a24a",
        fontWeight: 700,
        textTransform: "uppercase" as const,
        letterSpacing: 0.8,
        textAlign: "left" as const,
    },
    menuItemActive: {
        background: "rgba(201, 162, 74, 0.22)",
        border: "1px solid rgba(201, 162, 74, 0.88)",
        color: "#f2d27a",
    },
    menuItemIndex: {
        minWidth: 18,
        opacity: 0.95,
    },
    menuItemText: {
        flex: 1,
    },
    previewPanel: {
        borderRadius: 2,
        border: "1px solid rgba(201, 162, 74, 0.55)",
        background: "rgba(0, 0, 0, 0.35)",
        padding: 14,
    },
    previewMediaFrame: {
        width: "100%",
        height: 140,
        borderRadius: 2,
        border: "1px solid rgba(201, 162, 74, 0.55)",
        background: "rgba(0, 0, 0, 0.6)",
        marginBottom: 12,
        overflow: "hidden" as const,
    },
    previewImage: {
        width: "100%",
        height: "100%",
        objectFit: "cover" as const,
        display: "block",
    },
    previewTitle: {
        fontSize: 16,
        fontWeight: 800,
        color: "#c9a24a",
        textTransform: "uppercase" as const,
        letterSpacing: 1.0,
        marginBottom: 8,
    },
    previewText: {
        fontSize: 13,
        lineHeight: 1.35,
        color: "rgba(255,255,255,0.75)",
        marginBottom: 12,
    },
    factsList: {
        display: "flex",
        flexDirection: "column" as const,
        gap: 8,
        marginBottom: 14,
    },
    factRow: {
        display: "flex",
        justifyContent: "space-between" as const,
        gap: 12,
    },
    factLabel: {
        color: "#c9a24a",
        fontWeight: 700,
        textTransform: "uppercase" as const,
        letterSpacing: 0.6,
        fontSize: 12,
    },
    factValue: {
        color: "rgba(255,255,255,0.75)",
        fontWeight: 600,
        fontSize: 12,
    },
    openCategoryButton: {
        width: "100%",
        padding: "12px 14px",
        borderRadius: 2,
        border: "1px solid rgba(201, 162, 74, 0.55)",
        background: "rgba(0, 0, 0, 0.35)",
        cursor: "pointer",
        color: "#c9a24a",
        fontWeight: 800,
        textTransform: "uppercase" as const,
        letterSpacing: 1.0,
    },
};