// Generated by scripts/generate-startup-splash-fallback.mjs from /videos/round13-startup-intro.mp4.
// Do not hand-edit; run npm run generate:splash-fallback.

export type StartupSplashFallbackFrame = {
    readonly index: number;
    readonly sourceTimeMs: number;
    readonly src: string;
};

export const STARTUP_SPLASH_FALLBACK_SOURCE_SHA256 = "ed38918437451b5985581738ec069dafac5f16e4d575c330348c33698c2fda6d";
export const STARTUP_SPLASH_FALLBACK_DURATION_MS = 8000;
export const STARTUP_SPLASH_FALLBACK_FRAME_WIDTH = 540;
export const STARTUP_SPLASH_FALLBACK_FRAME_HEIGHT = 304;
export const STARTUP_SPLASH_FALLBACK_FRAMES = [
    {
        "index": 0,
        "sourceTimeMs": 0,
        "src": "/generated/startup-splash-fallback/frame-000.webp"
    },
    {
        "index": 1,
        "sourceTimeMs": 255,
        "src": "/generated/startup-splash-fallback/frame-001.webp"
    },
    {
        "index": 2,
        "sourceTimeMs": 511,
        "src": "/generated/startup-splash-fallback/frame-002.webp"
    },
    {
        "index": 3,
        "sourceTimeMs": 766,
        "src": "/generated/startup-splash-fallback/frame-003.webp"
    },
    {
        "index": 4,
        "sourceTimeMs": 1022,
        "src": "/generated/startup-splash-fallback/frame-004.webp"
    },
    {
        "index": 5,
        "sourceTimeMs": 1277,
        "src": "/generated/startup-splash-fallback/frame-005.webp"
    },
    {
        "index": 6,
        "sourceTimeMs": 1533,
        "src": "/generated/startup-splash-fallback/frame-006.webp"
    },
    {
        "index": 7,
        "sourceTimeMs": 1788,
        "src": "/generated/startup-splash-fallback/frame-007.webp"
    },
    {
        "index": 8,
        "sourceTimeMs": 2044,
        "src": "/generated/startup-splash-fallback/frame-008.webp"
    },
    {
        "index": 9,
        "sourceTimeMs": 2299,
        "src": "/generated/startup-splash-fallback/frame-009.webp"
    },
    {
        "index": 10,
        "sourceTimeMs": 2555,
        "src": "/generated/startup-splash-fallback/frame-010.webp"
    },
    {
        "index": 11,
        "sourceTimeMs": 2810,
        "src": "/generated/startup-splash-fallback/frame-011.webp"
    },
    {
        "index": 12,
        "sourceTimeMs": 3066,
        "src": "/generated/startup-splash-fallback/frame-012.webp"
    },
    {
        "index": 13,
        "sourceTimeMs": 3321,
        "src": "/generated/startup-splash-fallback/frame-013.webp"
    },
    {
        "index": 14,
        "sourceTimeMs": 3577,
        "src": "/generated/startup-splash-fallback/frame-014.webp"
    },
    {
        "index": 15,
        "sourceTimeMs": 3832,
        "src": "/generated/startup-splash-fallback/frame-015.webp"
    },
    {
        "index": 16,
        "sourceTimeMs": 4088,
        "src": "/generated/startup-splash-fallback/frame-016.webp"
    },
    {
        "index": 17,
        "sourceTimeMs": 4343,
        "src": "/generated/startup-splash-fallback/frame-017.webp"
    },
    {
        "index": 18,
        "sourceTimeMs": 4599,
        "src": "/generated/startup-splash-fallback/frame-018.webp"
    },
    {
        "index": 19,
        "sourceTimeMs": 4854,
        "src": "/generated/startup-splash-fallback/frame-019.webp"
    },
    {
        "index": 20,
        "sourceTimeMs": 5110,
        "src": "/generated/startup-splash-fallback/frame-020.webp"
    },
    {
        "index": 21,
        "sourceTimeMs": 5365,
        "src": "/generated/startup-splash-fallback/frame-021.webp"
    },
    {
        "index": 22,
        "sourceTimeMs": 5621,
        "src": "/generated/startup-splash-fallback/frame-022.webp"
    },
    {
        "index": 23,
        "sourceTimeMs": 5876,
        "src": "/generated/startup-splash-fallback/frame-023.webp"
    },
    {
        "index": 24,
        "sourceTimeMs": 6132,
        "src": "/generated/startup-splash-fallback/frame-024.webp"
    },
    {
        "index": 25,
        "sourceTimeMs": 6387,
        "src": "/generated/startup-splash-fallback/frame-025.webp"
    },
    {
        "index": 26,
        "sourceTimeMs": 6643,
        "src": "/generated/startup-splash-fallback/frame-026.webp"
    },
    {
        "index": 27,
        "sourceTimeMs": 6898,
        "src": "/generated/startup-splash-fallback/frame-027.webp"
    },
    {
        "index": 28,
        "sourceTimeMs": 7154,
        "src": "/generated/startup-splash-fallback/frame-028.webp"
    },
    {
        "index": 29,
        "sourceTimeMs": 7409,
        "src": "/generated/startup-splash-fallback/frame-029.webp"
    },
    {
        "index": 30,
        "sourceTimeMs": 7665,
        "src": "/generated/startup-splash-fallback/frame-030.webp"
    },
    {
        "index": 31,
        "sourceTimeMs": 7920,
        "src": "/generated/startup-splash-fallback/frame-031.webp"
    }
] as const satisfies readonly StartupSplashFallbackFrame[];
