package com.round13.backend.module.loyalty.domain;

public enum LoyaltyPointSourceType {
    TRAINING_VISIT,
    TRAINING_STREAK_BONUS,
    TRAINING_MONTHLY_MILESTONE,
    CLUB_EVENT_ATTENDANCE,
    RECRUITMENT,
    INITIATION,
    FITNESS_NORM_IMPROVEMENT,
    MONTHLY_COMPLEX_PLACEMENT,
    CLAN_WAR_PLACEMENT,
    PHYSICAL_PREPARATION_CHAMPIONSHIP,
    BOXING_MATCH,
    MANUAL_ADJUSTMENT,
    CORRECTION,
    REVERSAL,
    MIGRATION_IMPORT
}
