import type { CSSProperties } from "react";

export const addEventModalStyles = {
    modalOverlay: {
        position: "fixed",
        inset: 0,
        zIndex: 1000,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        padding: "16px",
        background: "rgba(4, 10, 18, 0.78)",
        backdropFilter: "blur(8px)",
    },
    modalCard: {
        width: "100%",
        maxWidth: "560px",
        maxHeight: "88vh",
        overflowY: "auto",
        display: "grid",
        gap: "14px",
        padding: "18px",
        borderRadius: "20px",
        border: "1px solid rgba(255,255,255,0.08)",
        background: "#17212b",
        boxShadow: "0 30px 70px rgba(0,0,0,0.35)",
    },
    modalHeader: {
        display: "grid",
        gap: "6px",
    },
    modalTitle: {
        margin: 0,
        fontSize: "20px",
        fontWeight: 800,
        color: "var(--tg-theme-text-color, #ffffff)",
    },
    modalHint: {
        margin: 0,
        fontSize: "13px",
        lineHeight: 1.45,
        color: "var(--tg-theme-hint-color, rgba(255,255,255,0.72))",
    },
    formGrid: {
        display: "grid",
        gap: "12px",
    },
    field: {
        display: "grid",
        gap: "6px",
    },
    fieldLabel: {
        fontSize: "13px",
        fontWeight: 600,
        color: "#9eb1c5",
    },
    selectWrap: {
        position: "relative",
    },
    selectButton: {
        width: "100%",
        minHeight: "46px",
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        gap: "12px",
        padding: "10px 12px",
        borderRadius: "10px",
        border: "1px solid rgba(255,255,255,0.08)",
        background: "#242f3d",
        color: "#ffffff",
        textAlign: "left",
        cursor: "pointer",
    },
    selectValueWrap: {
        display: "block",
        minWidth: 0,
    },
    selectValue: {
        fontSize: "15px",
        fontWeight: 700,
        color: "#ffffff",
    },
    selectChevron: {
        flexShrink: 0,
        fontSize: "12px",
        color: "#9eb1c5",
    },
    dropdownList: {
        position: "absolute",
        top: "calc(100% + 6px)",
        left: 0,
        right: 0,
        zIndex: 5,
        display: "grid",
        gap: "6px",
        padding: "8px",
        borderRadius: "14px",
        border: "1px solid rgba(255,255,255,0.08)",
        background: "#1b2632",
        boxShadow: "0 20px 40px rgba(0,0,0,0.28)",
    },
    dropdownItem: {
        width: "100%",
        display: "block",
        padding: "10px 12px",
        borderRadius: "10px",
        border: "1px solid transparent",
        background: "transparent",
        color: "#ffffff",
        textAlign: "left",
        cursor: "pointer",
    },
    dropdownItemActive: {
        border: "1px solid rgba(106,179,243,0.45)",
        background: "rgba(106,179,243,0.14)",
    },
    dropdownItemTitle: {
        fontSize: "14px",
        fontWeight: 700,
        color: "inherit",
    },
    input: {
        width: "100%",
        minHeight: "42px",
        padding: "10px 12px",
        borderRadius: "10px",
        border: "1px solid rgba(255,255,255,0.08)",
        background: "#242f3d",
        color: "#ffffff",
        boxSizing: "border-box",
    },
    textarea: {
        width: "100%",
        minHeight: "110px",
        padding: "10px 12px",
        borderRadius: "10px",
        border: "1px solid rgba(255,255,255,0.08)",
        background: "#242f3d",
        color: "#ffffff",
        boxSizing: "border-box",
        resize: "vertical",
        fontFamily: "inherit",
    },
    timeRow: {
        display: "grid",
        gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
        gap: "12px",
    },
    modalActions: {
        display: "grid",
        gap: "10px",
    },
} satisfies Record<string, CSSProperties>;
