export const QA_REFERENCE_DATE = process.env.QA_REFERENCE_DATE?.trim() || "2026-05-20";
export const QA_PANEL_ADMIN_PASSWORD = process.env.QA_PANEL_ADMIN_PASSWORD?.trim() || "qa-password";
export const QA_ORDER_ID = "order-regression-0001";

export const QA_USERS = {
    admin: {
        id: "00000000-0000-0000-0000-000000000001",
        nickname: "qa_admin",
        fullName: "QA Admin",
        role: "ADMIN",
        phone: "+79990000001",
        telegramUserId: 900001,
        avatarUrl: "https://static.round13.local/qa-admin.png",
    },
    coach: {
        id: "00000000-0000-0000-0000-000000000002",
        nickname: "coach_ivan",
        fullName: "Иван Тренер",
        role: "COACH",
        phone: "+79990000002",
        telegramUserId: 900002,
        avatarUrl: "https://static.round13.local/coach-ivan.png",
    },
    athlete: {
        id: "00000000-0000-0000-0000-000000000003",
        nickname: "athlete_katya",
        fullName: "Катя Атлет",
        role: "ATHLETE",
        phone: "+79990000003",
        telegramUserId: 900003,
        avatarUrl: "https://static.round13.local/athlete-katya.png",
    },
} as const;

export type QaRole = keyof typeof QA_USERS;

export const QA_SHOP_CATEGORY = {
    id: "30000000-0000-0000-0000-000000000001",
    title: "Экипировка",
    description: "Локальная QA категория для регрессионных тестов",
    type: "MERCH",
    isActive: true,
};

export const QA_SHOP_PRODUCTS = [
    {
        id: "31000000-0000-0000-0000-000000000001",
        code: "r13-tshirt-black",
        title: "Футболка Round13",
        description: "Черная клубная футболка",
        categoryId: QA_SHOP_CATEGORY.id,
        categoryTitle: QA_SHOP_CATEGORY.title,
        category: "MERCH",
        priceAmount: 250000,
        currency: "RUB",
        isActive: true,
        sortOrder: 10,
        entitlementType: null,
        entitlementQuantity: null,
        trainerId: null,
    },
    {
        id: "31000000-0000-0000-0000-000000000002",
        code: "group-8",
        title: "8 групповых тренировок",
        description: "Пакет групповых тренировок",
        categoryId: QA_SHOP_CATEGORY.id,
        categoryTitle: QA_SHOP_CATEGORY.title,
        category: "PACKAGE",
        priceAmount: 800000,
        currency: "RUB",
        isActive: true,
        sortOrder: 20,
        entitlementType: "GROUP_TRAININGS",
        entitlementQuantity: 8,
        trainerId: null,
    },
    {
        id: "31000000-0000-0000-0000-000000000003",
        code: "personal-ivan-4",
        title: "4 персональные с Иваном",
        description: "Пакет персональных тренировок",
        categoryId: QA_SHOP_CATEGORY.id,
        categoryTitle: QA_SHOP_CATEGORY.title,
        category: "PERSONAL",
        priceAmount: 1200000,
        currency: "RUB",
        isActive: true,
        sortOrder: 30,
        entitlementType: "PERSONAL_TRAININGS",
        entitlementQuantity: 4,
        trainerId: QA_USERS.coach.id,
    },
] as const;

export const QA_CLUB_EVENT = {
    id: "40000000-0000-0000-0000-000000000001",
    title: "Открытая тренировка для новичков",
    description: "Вводное занятие для новых участников клуба",
    type: "OPEN_TRAINING",
    startsAt: `${QA_REFERENCE_DATE}T18:00:00+03:00`,
    endsAt: `${QA_REFERENCE_DATE}T19:00:00+03:00`,
    location: "Зал Round13",
    createdByUserId: QA_USERS.coach.id,
    createdByName: QA_USERS.coach.fullName,
    trainerUserId: QA_USERS.coach.id,
    trainerName: QA_USERS.coach.nickname,
    joinedByMe: false,
    requiresGroupPackage: false,
    remainingGroupTrainings: 8,
};

export const QA_MY_SCHEDULE = [
    {
        sessionId: "50000000-0000-0000-0000-000000000001",
        title: "Персональная техника",
        type: "PERSONAL",
        startsAt: `${QA_REFERENCE_DATE}T12:00:00+03:00`,
        endsAt: `${QA_REFERENCE_DATE}T13:00:00+03:00`,
        coachId: QA_USERS.coach.id,
        coachName: QA_USERS.coach.nickname,
        coachAvatarUrl: QA_USERS.coach.avatarUrl,
        location: "Зал Round13",
        status: "BOOKED",
        canCancel: true,
    },
    {
        sessionId: "50000000-0000-0000-0000-000000000002",
        title: "Групповая выносливость",
        type: "GROUP",
        startsAt: `${QA_REFERENCE_DATE}T14:00:00+03:00`,
        endsAt: `${QA_REFERENCE_DATE}T15:00:00+03:00`,
        coachId: QA_USERS.coach.id,
        coachName: QA_USERS.coach.nickname,
        coachAvatarUrl: QA_USERS.coach.avatarUrl,
        location: "Зал Round13",
        status: "BOOKED",
        canCancel: true,
    },
    {
        sessionId: "50000000-0000-0000-0000-000000000003",
        title: "Персональная отмена ожидает подтверждения",
        type: "PERSONAL",
        startsAt: `${QA_REFERENCE_DATE}T16:00:00+03:00`,
        endsAt: `${QA_REFERENCE_DATE}T17:00:00+03:00`,
        coachId: QA_USERS.coach.id,
        coachName: QA_USERS.coach.nickname,
        coachAvatarUrl: QA_USERS.coach.avatarUrl,
        location: "Зал Round13",
        status: "CANCEL_REQUESTED",
        canCancel: false,
    },
    {
        sessionId: "50000000-0000-0000-0000-000000000004",
        title: "Персональная работа на лапах",
        type: "PERSONAL",
        startsAt: "2026-05-19T12:00:00+03:00",
        endsAt: "2026-05-19T13:00:00+03:00",
        coachId: QA_USERS.coach.id,
        coachName: QA_USERS.coach.nickname,
        coachAvatarUrl: QA_USERS.coach.avatarUrl,
        location: "Зал Round13",
        status: "ATTENDED",
        canCancel: false,
    },
    {
        sessionId: "50000000-0000-0000-0000-000000000005",
        title: "Групповая техника защиты",
        type: "GROUP",
        startsAt: "2026-05-19T14:00:00+03:00",
        endsAt: "2026-05-19T15:00:00+03:00",
        coachId: QA_USERS.coach.id,
        coachName: QA_USERS.coach.nickname,
        coachAvatarUrl: QA_USERS.coach.avatarUrl,
        location: "Зал Round13",
        status: "ATTENDED",
        canCancel: false,
    },
    {
        sessionId: "50000000-0000-0000-0000-000000000006",
        title: "Персональная отменена тренером",
        type: "PERSONAL",
        startsAt: `${QA_REFERENCE_DATE}T18:00:00+03:00`,
        endsAt: `${QA_REFERENCE_DATE}T19:00:00+03:00`,
        coachId: QA_USERS.coach.id,
        coachName: QA_USERS.coach.nickname,
        coachAvatarUrl: QA_USERS.coach.avatarUrl,
        location: "Зал Round13",
        status: "CANCELLED_BY_TRAINER",
        canCancel: false,
    },
    {
        sessionId: "50000000-0000-0000-0000-000000000007",
        title: "Персональная неявка QA",
        type: "PERSONAL",
        startsAt: "2026-05-19T18:00:00+03:00",
        endsAt: "2026-05-19T19:00:00+03:00",
        coachId: QA_USERS.coach.id,
        coachName: QA_USERS.coach.nickname,
        coachAvatarUrl: QA_USERS.coach.avatarUrl,
        location: "Зал Round13",
        status: "NO_SHOW",
        canCancel: false,
    },
] as const;

export const QA_PANEL_USERS = [
    {
        id: QA_USERS.admin.id,
        nickname: QA_USERS.admin.nickname,
        phone: QA_USERS.admin.phone,
        status: "ACTIVE",
        roleCode: "ADMIN",
    },
    {
        id: QA_USERS.coach.id,
        nickname: QA_USERS.coach.nickname,
        phone: QA_USERS.coach.phone,
        status: "ACTIVE",
        roleCode: "COACH",
    },
    {
        id: QA_USERS.athlete.id,
        nickname: QA_USERS.athlete.nickname,
        phone: QA_USERS.athlete.phone,
        status: "ACTIVE",
        roleCode: "ATHLETE",
    },
] as const;

export const QA_ERROR_JOURNAL_EVENT = {
    id: "70000000-0000-0000-0000-000000000001",
    occurredAt: "2026-07-02T09:30:00Z",
    createdAt: "2026-07-02T09:30:01Z",
    severity: "ERROR",
    source: "BACKEND",
    status: "OPEN",
    errorCode: "INTERNAL_ERROR",
    httpStatus: 500,
    exceptionClass: "java.lang.IllegalStateException",
    errorType: "IllegalStateException",
    message: "Leaderboard failed",
    stackTrace: "java.lang.IllegalStateException: Leaderboard failed\n\tat com.round13.backend.module.members.potential.BoxerPotentialService.leaderboard(BoxerPotentialService.java:120)",
    requestMethod: "GET",
    requestPath: "/api/members/boxer-potential/leaderboard",
    queryString: "token=%5Bredacted%5D",
    requestId: "qa-request-1",
    fingerprint: "a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2",
    actorUserId: QA_USERS.coach.id,
    panelAdminId: null,
    remoteAddr: "127.0.0.1",
    userAgent: "QA browser",
    resolutionNote: null,
    resolvedAt: null,
    resolvedByUserId: null,
} as const;

export const QA_MY_STATS = {
    ratingPlace: 7,
    clubExperienceMonths: 14,
    fightsCount: 5,
    winsCount: 3,
    defeatsCount: 2,
    sparringsCount: 9,
    trainingsAttendedCount: 42,
    trainingsMissedCount: 4,
    winRatePercent: 60,
    knockoutRatePercent: 20,
    knockdownRatePercent: 40,
};

export const QA_BOXER_POTENTIAL_SUMMARY = {
    latest: {
        id: "80000000-0000-0000-0000-000000000001",
        memberId: QA_USERS.athlete.id,
        measuredAt: "2026-08-20T12:00:00Z",
        createdAt: "2026-08-20T12:01:00Z",
        updatedAt: "2026-08-20T12:01:00Z",
        createdByUserId: QA_USERS.coach.id,
        createdByName: QA_USERS.coach.fullName,
        updatedByUserId: null,
        updatedByName: null,
        normGroup: "FEMALE",
        normGroupLabel: "Женщины",
        normSet: "FEMALE_CHILD",
        ageAtMeasurement: 31,
        genderAtMeasurement: "FEMALE",
        raw: {
            pushUps90Sec: 35,
            pullUps: 8,
            jumpSquats90Sec: 48,
            punchForceKg: 90,
            burpees5Min: 54,
            punches20Sec: 62,
            ropeJumps60Sec: 154,
            doubleUnders60Sec: 34,
        },
        testScores: {
            pushUpsScore: 35,
            pullUpsScore: 20,
            jumpSquatsScore: 60,
            punchForceScore: 60,
            burpeesScore: 54,
            punchesScore: 77.5,
            ropeJumpsScore: 70,
            doubleUndersScore: 30.9,
        },
        characteristicScores: {
            strength: 43.8,
            endurance: 54,
            speed: 77.5,
            agility: 50.5,
        },
        potentialScore: 56.5,
    },
    history: [
        {
            id: "80000000-0000-0000-0000-000000000001",
            memberId: QA_USERS.athlete.id,
            measuredAt: "2026-08-20T12:00:00Z",
            createdAt: "2026-08-20T12:01:00Z",
            updatedAt: "2026-08-20T12:01:00Z",
            createdByUserId: QA_USERS.coach.id,
            createdByName: QA_USERS.coach.fullName,
            updatedByUserId: null,
            updatedByName: null,
            normGroup: "FEMALE",
            normGroupLabel: "Женщины",
            normSet: "FEMALE_CHILD",
            ageAtMeasurement: 31,
            genderAtMeasurement: "FEMALE",
            raw: {
                pushUps90Sec: 35,
                pullUps: 8,
                jumpSquats90Sec: 48,
                punchForceKg: 90,
                burpees5Min: 54,
                punches20Sec: 62,
                ropeJumps60Sec: 154,
                doubleUnders60Sec: 34,
            },
            testScores: {
                pushUpsScore: 35,
                pullUpsScore: 20,
                jumpSquatsScore: 60,
                punchForceScore: 60,
                burpeesScore: 54,
                punchesScore: 77.5,
                ropeJumpsScore: 70,
                doubleUndersScore: 30.9,
            },
            characteristicScores: {
                strength: 43.8,
                endurance: 54,
                speed: 77.5,
                agility: 50.5,
            },
            potentialScore: 56.5,
        },
        {
            id: "80000000-0000-0000-0000-000000000002",
            memberId: QA_USERS.athlete.id,
            measuredAt: "2026-08-14T12:00:00Z",
            createdAt: "2026-08-14T12:01:00Z",
            updatedAt: "2026-08-14T12:01:00Z",
            createdByUserId: QA_USERS.coach.id,
            createdByName: QA_USERS.coach.fullName,
            updatedByUserId: null,
            updatedByName: null,
            normGroup: "FEMALE",
            normGroupLabel: "Женщины",
            normSet: "FEMALE_CHILD",
            ageAtMeasurement: 31,
            genderAtMeasurement: "FEMALE",
            raw: {
                pushUps90Sec: 30,
                pullUps: 6,
                jumpSquats90Sec: 42,
                punchForceKg: 82,
                burpees5Min: 48,
                punches20Sec: 58,
                ropeJumps60Sec: 140,
                doubleUnders60Sec: 28,
            },
            testScores: {
                pushUpsScore: 30,
                pullUpsScore: 15,
                jumpSquatsScore: 52.5,
                punchForceScore: 54.7,
                burpeesScore: 48,
                punchesScore: 72.5,
                ropeJumpsScore: 63.6,
                doubleUndersScore: 25.5,
            },
            characteristicScores: {
                strength: 38.1,
                endurance: 48,
                speed: 72.5,
                agility: 44.6,
            },
            potentialScore: 50.8,
        },
        {
            id: "80000000-0000-0000-0000-000000000003",
            memberId: QA_USERS.athlete.id,
            measuredAt: "2026-07-15T12:00:00Z",
            createdAt: "2026-07-15T12:01:00Z",
            updatedAt: "2026-07-15T12:01:00Z",
            createdByUserId: QA_USERS.coach.id,
            createdByName: QA_USERS.coach.fullName,
            updatedByUserId: null,
            updatedByName: null,
            normGroup: "FEMALE",
            normGroupLabel: "Женщины",
            normSet: "FEMALE_CHILD",
            ageAtMeasurement: 31,
            genderAtMeasurement: "FEMALE",
            raw: {
                pushUps90Sec: 24,
                pullUps: 5,
                jumpSquats90Sec: 36,
                punchForceKg: 74,
                burpees5Min: 42,
                punches20Sec: 52,
                ropeJumps60Sec: 124,
                doubleUnders60Sec: 20,
            },
            testScores: {
                pushUpsScore: 24,
                pullUpsScore: 12.5,
                jumpSquatsScore: 45,
                punchForceScore: 49.3,
                burpeesScore: 42,
                punchesScore: 65,
                ropeJumpsScore: 56.4,
                doubleUndersScore: 18.2,
            },
            characteristicScores: {
                strength: 32.7,
                endurance: 42,
                speed: 65,
                agility: 37.3,
            },
            potentialScore: 44.3,
        },
    ],
    chart: [
        {
            measuredAt: "2026-07-15T12:00:00Z",
            potentialScore: 44.3,
            strengthScore: 32.7,
            enduranceScore: 42,
            speedScore: 65,
            agilityScore: 37.3,
        },
        {
            measuredAt: "2026-08-14T12:00:00Z",
            potentialScore: 50.8,
            strengthScore: 38.1,
            enduranceScore: 48,
            speedScore: 72.5,
            agilityScore: 44.6,
        },
        {
            measuredAt: "2026-08-20T12:00:00Z",
            potentialScore: 56.5,
            strengthScore: 43.8,
            enduranceScore: 54,
            speedScore: 77.5,
            agilityScore: 50.5,
        },
    ],
    canCreateMeasurement: false,
    createBlockedReason: "Замеры может добавлять тренер.",
} as const;

export function meResponse(role: QaRole) {
    const user = QA_USERS[role];

    return {
        id: user.id,
        phone: user.phone,
        nickname: user.nickname,
        role: user.role,
        status: "ACTIVE",
        telegramUserId: user.telegramUserId,
        fullName: user.fullName,
        birthDate: "1995-01-01",
        avatarUrl: user.avatarUrl,
        gender: role === "athlete" ? "FEMALE" : "MALE",
        profileCompleted: true,
        debutDate: "2024-01-01",
        clan: "Round13 QA",
        aboutMe: "Локальный QA профиль",
        phoneVerifiedByStaff: true,
        entitlements: [],
    };
}
