import { FormEvent, useEffect, useState } from "react";
import { panelHttp } from "../../../shared/api/panelHttp";
import AdminGuard from "../shared/ui/AdminGuard/AdminGuard";
import PanelAdminNav from "../shared/ui/components/PanelAdminNav/PanelAdminNav";

type Space={id:string;displayName:string;spreadsheetUrl:string;spreadsheetId:string;serviceAccountEmail:string|null;credentialsEnvVar:string|null;accessDetails:string|null;active:boolean;credentialsAvailable:boolean};
const initial={displayName:"",spreadsheetUrl:"",spreadsheetId:"",serviceAccountEmail:"",credentialsEnvVar:"GOOGLE_SHEETS_SERVICE_ACCOUNT_JSON",accessDetails:"",active:false};
const ui={page:{minHeight:"100vh",background:"#0b1220",color:"#e6edf3",padding:24,fontFamily:"system-ui"},panel:{maxWidth:1000,margin:"auto",background:"#17202d",padding:20,borderRadius:16},form:{display:"grid",gap:10,margin:"18px 0"},input:{padding:11,borderRadius:9,border:"1px solid #ffffff30",background:"#0d1520",color:"white"},button:{padding:"10px 14px",border:0,borderRadius:9,background:"#c8322c",color:"white",cursor:"pointer"},card:{padding:14,background:"#0d1520",borderRadius:12,marginTop:10}} as const;

export function AdminGoogleSheetsPage(){const [spaces,setSpaces]=useState<Space[]>([]),[form,setForm]=useState(initial),[message,setMessage]=useState("");const load=async()=>setSpaces((await panelHttp.get<Space[]>("/panel/google-sheet-spaces")).data);useEffect(()=>{void load()},[]);async function submit(e:FormEvent){e.preventDefault();setMessage("");try{await panelHttp.post("/panel/google-sheet-spaces",form);setForm(initial);await load()}catch{setMessage("Не удалось сохранить настройки")}}async function activate(id:string){await panelHttp.post(`/panel/google-sheet-spaces/${id}/activate`);await load()}async function test(id:string){setMessage("Проверка…");try{const r=await panelHttp.post<{message:string}>(`/panel/google-sheet-spaces/${id}/test`);setMessage(r.data.message)}catch(e:any){setMessage(e.response?.data?.message??"Нет доступа к Google Sheets")}}return <AdminGuard><main style={ui.page}><section style={ui.panel}><h1>Google Sheets · Schedule 2.0</h1><PanelAdminNav/><p>Ключ не сохраняется в базе: задайте JSON service account в указанной переменной окружения.</p><form style={ui.form} onSubmit={submit}>{(["displayName","spreadsheetUrl","spreadsheetId","serviceAccountEmail","credentialsEnvVar","accessDetails"] as const).map(k=><input required={k==="displayName"||k==="spreadsheetUrl"||k==="spreadsheetId"} key={k} style={ui.input} placeholder={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Сделать активным</label><button style={ui.button}>Сохранить пространство</button></form>{message&&<p>{message}</p>}{spaces.map(s=><article key={s.id} style={ui.card}><b>{s.displayName} {s.active&&"· АКТИВНО"}</b><p>{s.spreadsheetId}</p><p>Credentials: {s.credentialsAvailable?"доступны":"не найдены"}</p><button style={ui.button} onClick={()=>void test(s.id)}>Проверить чтение/запись</button>{!s.active&&<button style={{...ui.button,marginLeft:8}} onClick={()=>void activate(s.id)}>Активировать</button>}</article>)}</section></main></AdminGuard>}
