ALTER TABLE users ADD COLUMN permanently_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN status_before_block VARCHAR(16);
ALTER TABLE users ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
