import type { CSSProperties } from "react";

export const scheduleTimePickerStyles = {
    overlay: {
        position: "fixed",
        inset: 0,
        zIndex: 1001,
        display: "flex",
        alignItems: "flex-end",
        justifyContent: "center",
        padding: "16px",
        background: "rgba(4, 10, 18, 0.5)",
    },
    card: {
        width: "100%",
        maxWidth: "420px",
        display: "grid",
        gap: "14px",
        padding: "18px",
        borderRadius: "20px",
        border: "1px solid rgba(255,255,255,0.08)",
        background: "#17212b",
        boxShadow: "0 30px 70px rgba(0,0,0,0.35)",
    },
    header: {
        display: "grid",
        gap: "4px",
    },
    title: {
        margin: 0,
        fontSize: "18px",
        fontWeight: 800,
        color: "var(--tg-theme-text-color, #ffffff)",
    },
    wheel: {
        position: "relative",
        display: "grid",
        gridTemplateColumns: "1fr auto 1fr",
        gap: "12px",
        alignItems: "stretch",
    },
    highlight: {
        position: "absolute",
        left: 0,
        right: 0,
        top: "50%",
        height: "44px",
        transform: "translateY(-50%)",
        borderRadius: "12px",
        background: "rgba(106,179,243,0.10)",
        border: "1px solid rgba(106,179,243,0.22)",
        pointerEvents: "none",
    },
    column: {
        position: "relative",
        height: "220px",
        overflow: "hidden",
    },
    scroll: {
        height: "220px",
        overflowY: "auto",
        scrollSnapType: "y mandatory",
        padding: "88px 0",
        scrollbarWidth: "none",
        msOverflowStyle: "none",
    },
    divider: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: "28px",
        fontWeight: 800,
        color: "#9eb1c5",
    },
    item: {
        width: "100%",
        height: "44px",
        border: "none",
        background: "transparent",
        color: "rgba(255,255,255,0.52)",
        fontSize: "26px",
        fontWeight: 700,
        scrollSnapAlign: "center",
        cursor: "pointer",
    },
    itemActive: {
        color: "#ffffff",
    },
    actions: {
        display: "grid",
        gap: "10px",
    },
} satisfies Record<string, CSSProperties>;
